In [1]:
# # initialize your variable to None
# lat_lng_coords = None

# # loop until you get the coordinates
# while(lat_lng_coords is None):
#     g = geocoder.google("{}, Toronto, Ontario".format(postal_code))
#     lat_lng_coords = g.latlng
    
# latitude = lat_lng_coords[0]
# longitude = lat_lng_coords[1]

import pandas as pd

In [2]:
#file paths for two data source files 
file = "Geospatial_Coordinates.csv"
file2 = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"

#read csv for the Geospatial file
read_file = pd.read_csv(file)
read_file.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [3]:
#read table from wikipedia
read_file2 = pd.read_html(file2)
read_file2 = read_file2[0]
read_file2.head()

  Postal code           Borough                Neighborhood
0         M1A      Not assigned                         NaN
1         M2A      Not assigned                         NaN
2         M3A        North York                   Parkwoods
3         M4A        North York            Victoria Village
4         M5A  Downtown Toronto  Regent Park / Harbourfront

In [4]:
#merge the two dataframes together
coordinates_df = pd.merge(read_file, read_file2, how='left', left_on = 'Postal Code', right_on = 'Postal code')
coordinates_df

,Postal Code,Latitude,Longitude,Postal code,Borough,Neighborhood
0,M1B,43.806686,-79.194353,M1B,Scarborough,Malvern / Rouge
1,M1C,43.784535,-79.160497,M1C,Scarborough,Rouge Hill / Port Union / Highland Creek
2,M1E,43.763573,-79.188711,M1E,Scarborough,Guildwood / Morningside / West Hill
3,M1G,43.770992,-79.216917,M1G,Scarborough,Woburn
4,M1H,43.773136,-79.239476,M1H,Scarborough,Cedarbrae
...,...,...,...,...,...,...
98,M9N,43.706876,-79.518188,M9N,York,Weston
99,M9P,43.696319,-79.532242,M9P,Etobicoke,Westmount
100,M9R,43.688905,-79.554724,M9R,Etobicoke,Kingsview Village / St. Phillips / Martin Grov...
101,M9V,43.739416,-79.588437,M9V,Etobicoke,South Steeles / Silverstone / Humbergate / Jam...
102,M9W,43.706748,-79.594054,M9W,Etobicoke,Northwest

In [5]:
# drop the "Postal code" column
coordinates_df.drop("Postal code", axis=1, inplace=True)
coordinates_df.head(11)

,Postal Code,Latitude,Longitude,Borough,Neighborhood
0,M1B,43.806686,-79.194353,Scarborough,Malvern / Rouge
1,M1C,43.784535,-79.160497,Scarborough,Rouge Hill / Port Union / Highland Creek
2,M1E,43.763573,-79.188711,Scarborough,Guildwood / Morningside / West Hill
3,M1G,43.770992,-79.216917,Scarborough,Woburn
4,M1H,43.773136,-79.239476,Scarborough,Cedarbrae
5,M1J,43.744734,-79.239476,Scarborough,Scarborough Village
6,M1K,43.727929,-79.262029,Scarborough,Kennedy Park / Ionview / East Birchmount Park
7,M1L,43.711112,-79.284577,Scarborough,Golden Mile / Clairlea / Oakridge
8,M1M,43.716316,-79.239476,Scarborough,Cliffside / Cliffcrest / Scarborough Village West
9,M1N,43.692657,-79.264848,Scarborough,Birch Cliff / Cliffside West
10,M1P,43.757410,-79.273304,Scarborough,Dorset Park / Wexford Heights / Scarborough To...

In [6]:
#print coordinate names
coordinates_df.columns

Index(['Postal Code', 'Latitude', 'Longitude', 'Borough', 'Neighborhood'], dtype='object')

In [7]:
#reorder the columns
coordinates_df = coordinates_df[['Postal Code', 'Borough', 'Latitude', 'Longitude', 'Neighborhood']]
coordinates_df.head(12)

,Postal Code,Borough,Latitude,Longitude,Neighborhood
0,M1B,Scarborough,43.806686,-79.194353,Malvern / Rouge
1,M1C,Scarborough,43.784535,-79.160497,Rouge Hill / Port Union / Highland Creek
2,M1E,Scarborough,43.763573,-79.188711,Guildwood / Morningside / West Hill
3,M1G,Scarborough,43.770992,-79.216917,Woburn
4,M1H,Scarborough,43.773136,-79.239476,Cedarbrae
5,M1J,Scarborough,43.744734,-79.239476,Scarborough Village
6,M1K,Scarborough,43.727929,-79.262029,Kennedy Park / Ionview / East Birchmount Park
7,M1L,Scarborough,43.711112,-79.284577,Golden Mile / Clairlea / Oakridge
8,M1M,Scarborough,43.716316,-79.239476,Cliffside / Cliffcrest / Scarborough Village West
9,M1N,Scarborough,43.692657,-79.264848,Birch Cliff / Cliffside West
10,M1P,Scarborough,43.757410,-79.273304,Dorset Park / Wexford Heights / Scarborough To...
11,M1R,Scarborough,43.750072,-79.295849,Wexford / Maryvale